data_directory: 'path/to/training/data'
image_processing:
  rescale: 1.0/255
  zoom_range: [1.0, 1.2]
  validation_split: 0.2
model_parameters:
  dropout_rate: 0.5
  learning_rate: 0.0001
training_parameters:
  epochs: 6
  batch_size: 32
